title: AI for Oncology Conference Deadlines
description: Countdowns to top conferences on AI/radiology/digital pathology/oncology
author: AI for Oncology lab (Netherlands Cancer Institute)

domain: "deadlines.aiforoncology.nl"
baseurl: ""

twitter_hashtag: AI4Oncology
github_username: NKI-AI
github_repo: conference-deadlines

markdown: kramdown
ga_id:

include: ['_pages']
